/**
 * Pre-compiled fallback dataset for standalone frontend deployments (e.g., Vercel static hosting).
 * Sourced directly from Q-Catalyst Phases 1-7 artifacts.
 */

import {
  CandidateDetailResponse,
  CandidatesListResponse,
  HealthResponse,
  OverviewResponse,
  PipelineResponse,
  ProvenanceResponse,
  QuantumDetailsResponse,
  QuantumHistoryResponse,
  StructureResponse,
} from '@/types/api';

export const fallbackHealth: HealthResponse = {
  status: 'ok',
  version: '0.1.0',
  app_name: 'Q-Catalyst API (Embedded Static Mode)',
  timestamp: new Date().toISOString(),
};

export const fallbackOverview: OverviewResponse = {
  target_enzyme: 'IsPETase',
  organism: 'Ideonella sakaiensis (PDB 5XJH)',
  active_run_id: 'run_phase7_orchestrator',
  total_candidates: 5,
  stages_completed: 7,
  total_stages: 7,
  top_candidate: {
    candidate_id: 'VAR_W132H',
    mature_mutation: 'W132H',
    crystal_mutation: 'W159H',
    role: 'Active-site aromatic cleft engineering',
    fusion_score: 0.8421,
    decision_status: 'PRIORITIZE',
    confidence_label: 'HIGH',
    evidence_coverage: '6/6',
  },
  quantum_highlight: {
    active_space: '4e, 4o',
    num_qubits: 8,
    num_pauli_terms: 61,
    casci_energy: -18.215733,
    vqe_energy: -18.206475,
    absolute_error: 0.009258,
    backend: 'qiskit_aer_statevector',
  },
  provenance_badge: 'SYNTHETIC_FIXTURE_EVALUATION',
};

export const fallbackCandidates: CandidatesListResponse = {
  count: 5,
  candidates: [
    {
      rank: 1,
      candidate_id: 'VAR_W132H',
      mutations: 'W132H',
      crystal_mutation: 'W159H',
      role: 'Active-site aromatic cleft engineering',
      fusion_score: 0.8421,
      decision_status: 'PRIORITIZE',
      confidence_label: 'HIGH',
      evidence_coverage: '6/6',
      protein_ai_score: 0.92,
      uncertainty_quality_score: 0.88,
      mechanism_proximity_score: 0.95,
      chemistry_score: 0.84,
      quantum_score: 0.91,
      diversity_score: 0.72,
      vqe_casci_error: 0.009258,
      quantum_available: true,
    },
    {
      rank: 2,
      candidate_id: 'VAR_S133A',
      mutations: 'S133A',
      crystal_mutation: 'S160A',
      role: 'Catalytic nucleophile mutation (Negative Control)',
      fusion_score: 0.3125,
      decision_status: 'LOW_PRIORITY',
      confidence_label: 'HIGH',
      evidence_coverage: '5/6',
      protein_ai_score: 0.45,
      uncertainty_quality_score: 0.82,
      mechanism_proximity_score: 0.12,
      chemistry_score: 0.28,
      quantum_score: null,
      diversity_score: 0.41,
      vqe_casci_error: null,
      quantum_available: false,
    },
    {
      rank: 3,
      candidate_id: 'VAR_D179A',
      mutations: 'D179A',
      crystal_mutation: 'D206A',
      role: 'Catalytic aspartate charge-relay knockout',
      fusion_score: 0.2984,
      decision_status: 'LOW_PRIORITY',
      confidence_label: 'MEDIUM',
      evidence_coverage: '5/6',
      protein_ai_score: 0.38,
      uncertainty_quality_score: 0.76,
      mechanism_proximity_score: 0.18,
      chemistry_score: 0.32,
      quantum_score: null,
      diversity_score: 0.45,
      vqe_casci_error: null,
      quantum_available: false,
    },
    {
      rank: 4,
      candidate_id: 'VAR_H210A',
      mutations: 'H210A',
      crystal_mutation: 'H237A',
      role: 'Catalytic histidine base knockout',
      fusion_score: 0.2812,
      decision_status: 'LOW_PRIORITY',
      confidence_label: 'MEDIUM',
      evidence_coverage: '5/6',
      protein_ai_score: 0.35,
      uncertainty_quality_score: 0.79,
      mechanism_proximity_score: 0.15,
      chemistry_score: 0.30,
      quantum_score: null,
      diversity_score: 0.48,
      vqe_casci_error: null,
      quantum_available: false,
    },
    {
      rank: 5,
      candidate_id: 'VAR_WT',
      mutations: 'WT (Wild Type)',
      crystal_mutation: 'WT',
      role: 'Wild-Type IsPETase reference baseline',
      fusion_score: 0.6514,
      decision_status: 'PROMISING_BUT_UNCERTAIN',
      confidence_label: 'HIGH',
      evidence_coverage: '6/6',
      protein_ai_score: 0.68,
      uncertainty_quality_score: 0.90,
      mechanism_proximity_score: 0.85,
      chemistry_score: 0.62,
      quantum_score: 0.75,
      diversity_score: 0.50,
      vqe_casci_error: 0.009258,
      quantum_available: true,
    },
  ],
};

export const fallbackCandidateDetails: Record<string, CandidateDetailResponse> = {
  VAR_W132H: {
    candidate: fallbackCandidates.candidates[0],
    radar_scores: {
      protein_ai: 0.92,
      uncertainty_quality: 0.88,
      mechanism_proximity: 0.95,
      chemistry: 0.84,
      quantum: 0.91,
      diversity: 0.72,
    },
    mature_numbering: 'Trp132His (Mature 1-263)',
    crystal_numbering: 'Trp159His (5XJH Crystal)',
    functional_role: 'Active-site aromatic cleft engineering',
    active_site_distance_angstrom: 4.82,
    conformal_lower_bound: 0.74,
    conformal_upper_bound: 0.96,
    explanation: {
      summary: 'Candidate VAR_W132H demonstrates top-tier sequence fitness and preserves the catalytic triad hydrogen-bonding network.',
      positive_factors: [
        'ESM sequence fitness score in top 5th percentile (0.92).',
        'Tight conformal confidence interval with high statistical certainty (0.88).',
        'Maintains optimal 4.82 Å spatial distance to Ser160-Asp206-His237 catalytic triad.',
        'TwoLocal VQE energy converges within 0.009258 Ha of CASCI ground state.',
      ],
      negative_factors: [],
      missing_evidence: [],
      limitations: [
        'Evaluation conducted on synthetic demonstration fixture.',
        'Quantum circuit executed on classical statevector simulator (Qiskit Aer).',
      ],
    },
  },
};

export const fallbackQuantum: QuantumDetailsResponse = {
  active_space_electrons: 4,
  active_space_orbitals: 4,
  num_qubits: 8,
  num_pauli_terms: 61,
  mapping_method: 'jordan_wigner',
  ansatz_type: 'TwoLocal (Ry-Rz)',
  optimizer: 'COBYLA',
  iterations: 30,
  casci_energy: -18.215733,
  vqe_energy: -18.206475,
  absolute_error: 0.009258,
  noise_enabled: false,
  noise_model: 'ideal_statevector',
  noisy_energy: null,
  noisy_error: null,
  backend: 'qiskit_aer_statevector_simulator',
  simulation_note: 'Jordan-Wigner mapped 8-qubit active space solved via TwoLocal ansatz and classical statevector diagonalization.',
};

export const fallbackQuantumHistory: QuantumHistoryResponse = {
  casci_reference_energy: -18.215733,
  final_vqe_energy: -18.206475,
  history: [
    { iteration: 1, energy: -17.854210 },
    { iteration: 5, energy: -18.012450 },
    { iteration: 10, energy: -18.145890 },
    { iteration: 15, energy: -18.189420 },
    { iteration: 20, energy: -18.201120 },
    { iteration: 25, energy: -18.205890 },
    { iteration: 30, energy: -18.206475 },
  ],
};

export const fallbackStructure: StructureResponse = {
  pdb_id: '5XJH',
  resolution_angstrom: 1.58,
  catalytic_groups: [
    {
      group_name: 'Catalytic Triad',
      residues: ['Ser160', 'Asp206', 'His237'],
      description: 'Canonical charge-relay system performing nucleophilic attack on PET ester carbonyl.',
    },
    {
      group_name: 'Oxyanion Hole',
      residues: ['Tyr87', 'Met161'],
      description: 'Stabilizes the tetrahedral oxyanion transition state via dual backbone hydrogen bonds.',
    },
    {
      group_name: 'Substrate Binding Cleft',
      residues: ['Trp159', 'Ile208', 'Trp185'],
      description: 'Hydrophobic wobble cleft accommodating the aromatic terephthalate polymer ring.',
    },
  ],
  distance_matrix: [
    {
      residue_pair: 'Ser160 (OG) — His237 (NE2)',
      distance_angstrom: 2.84,
      functional_state: 'Active Hydrogen Bond',
      status: 'PRESERVED',
    },
    {
      residue_pair: 'His237 (ND1) — Asp206 (OD2)',
      distance_angstrom: 2.71,
      functional_state: 'Charge Relay Salt Bridge',
      status: 'PRESERVED',
    },
    {
      residue_pair: 'Trp159 (CZ2) — Ser160 (OG)',
      distance_angstrom: 4.82,
      functional_state: 'Wobble Cleft Gateway',
      status: 'PERMISSIBLE',
    },
  ],
  mechanism_gate_cutoff_angstrom: 6.0,
};

export const fallbackPipeline: PipelineResponse = {
  pipeline_version: '0.1.0',
  run_id: 'run_phase7_orchestrator',
  timestamp: '2026-10-07T16:05:33Z',
  all_stages_successful: true,
  stages: [
    {
      stage_id: 'stage_1_data',
      name: 'Stage 1: Data Foundation & Structure Mapping',
      status: 'SUCCESS',
      duration_seconds: 0.0421,
      description: 'Validated 5XJH crystal structure coordinates and residue numbering.',
      artifact_path: 'data/processed/candidates_phase1.parquet',
    },
    {
      stage_id: 'stage_2_protein_ai',
      name: 'Stage 2: Protein AI & Conformal Calibration',
      status: 'SUCCESS',
      duration_seconds: 0.1184,
      description: 'ESM mutational embeddings with non-conformity score bounds.',
      artifact_path: 'models/uncertainty/conformal_calibration.json',
    },
    {
      stage_id: 'stage_3_acquisition',
      name: 'Stage 3: Mechanism-Aware Acquisition',
      status: 'SUCCESS',
      duration_seconds: 0.0315,
      description: 'Proximity filtering to catalytic triad with diversity preservation.',
      artifact_path: 'acquisition/selected_candidates.parquet',
    },
    {
      stage_id: 'stage_4_chemistry',
      name: 'Stage 4: Classical Active-Site Chemistry',
      status: 'SUCCESS',
      duration_seconds: 0.0892,
      description: 'Classical active-space cluster extraction for 5XJH.',
      artifact_path: 'chemistry/active_space_integrals.json',
    },
    {
      stage_id: 'stage_5_quantum',
      name: 'Stage 5: 8-Qubit Hamiltonian & VQE',
      status: 'SUCCESS',
      duration_seconds: 0.2451,
      description: '61 Pauli term Hamiltonian solved via CASCI and TwoLocal VQE.',
      artifact_path: 'quantum/quantum_manifest.json',
    },
    {
      stage_id: 'stage_6_fusion',
      name: 'Stage 6: Multimodal Evidence Fusion',
      status: 'SUCCESS',
      duration_seconds: 0.0210,
      description: 'Dynamic evidence renormalization and deterministic explainability.',
      artifact_path: 'decision/candidate_rankings.parquet',
    },
    {
      stage_id: 'stage_7_orchestrator',
      name: 'Stage 7: End-to-End Orchestration',
      status: 'SUCCESS',
      duration_seconds: 0.5473,
      description: 'Complete pipeline lineage execution and verification.',
      artifact_path: 'manifests/run_manifest.json',
    },
  ],
};

export const fallbackProvenance: ProvenanceResponse = {
  quantum_backend: 'Qiskit Aer Statevector (Ideal Simulation)',
  data_quality_tier: 'SYNTHETIC_FIXTURE_EVALUATION',
  software_stack: {
    'Python Scientific Core': '3.11+ / NumPy / SciPy / PyPDB',
    'Quantum Simulation': 'Qiskit / Qiskit Aer / Qiskit Algorithms',
    'Machine Learning & Conformal': 'PyTorch / ESM-2 / Scikit-Learn',
    'Frontend Engine': 'React 18 / TypeScript / Vite / Tailwind CSS',
    'Visual Analytics': 'Recharts / Lucide Icons',
  },
  disclaimers: [
    {
      category: 'Quantum Simulation Scope',
      title: 'Algorithmic Simulation Only',
      description: 'All quantum eigensolver calculations are simulated via statevector emulation. No physical quantum hardware execution or quantum supremacy is claimed.',
    },
    {
      category: 'Data Provenance',
      title: 'In-Silico Demonstration Fixture',
      description: 'Mutational profiles are generated on controlled synthetic fixtures. No real PET-Gym or wet-lab experimental kinetics are fabricated.',
    },
    {
      category: 'Catalytic Mechanism',
      title: 'Residue Indexing Harmonization',
      description: 'IsPETase mature sequence (residues 1–263) is rigorously mapped to PDB 5XJH crystal precursor coordinates (+27 offset).',
    },
  ],
};
